### ISSUE TITLE
最新版本报错

### ISSUE THREAD

**Issue by linkser** [rokam/midea-local#250]
v2.4.0:
Traceback (most recent call last):
  File "F:\PycharmProjects\pythonProject\dfdsf\setattr2.py", line 34, in <module>
    ac.set_attribute("mode", 2)
  File "F:\PycharmProjects\pythonProject\.venv\Lib\site-packages\midealocal\devices\ac\__init__.py", line 375, in set_attribute
    self.build_send(message)
  File "F:\PycharmProjects\pythonProject\.venv\Lib\site-packages\midealocal\device.py", line 286, in build_send
    self.send_message(msg)
  File "F:\PycharmProjects\pythonProject\.venv\Lib\site-packages\midealocal\device.py", line 257, in send_message
    self.send_message_v3(data, msg_type=MSGTYPE_ENCRYPTED_REQUEST)
  File "F:\PycharmProjects\pythonProject\.venv\Lib\site-packages\midealocal\device.py", line 278, in send_message_v3
    data = self._security.encode_8370(data, msg_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PycharmProjects\pythonProject\.venv\Lib\site-packages\midealocal\security.py", line 329, in encode_8370
    data = self.aes_cbc_encrypt(raw=data, key=self._tcp_key) + sign
                                              ^^^^^^^^^^^^^
AttributeError: 'LocalSecurity' object has no attribute '_tcp_key'. Did you mean: 'tcp_key'?

**Comment by rokam** [comment]
Did you device.connect() before trying to set the mode? V3 devices need to authenticate to exchange security keys.

**Comment by linkser** [comment]
> Did you device.connect() before trying to set the mode? V3 devices need to authenticate to exchange security keys.

yes,i did device.connect() before that .and the same code works fine at v2.3.0

**Comment by rokam** [comment]
You need to call `device.authenticate()` too
